Changes to address errors that Dave experienced

diff --git a/merge_updates b/merge_updates
--- a/merge_updates
+++ b/merge_updates
@@ -101,47 +101,51 @@ else
 fi
 
 #now process each of the full dump files with the single merged update file
+full_dump_files=`find $DUMPDIR -name "*.mrc" | wc -l`
 
-endId=000000000
+if [[ "$full_dump_files" != "0" ]] ; then
 
-for file in $DUMPDIR/*.mrc 
-do
-    file0=`dirname $file`
-    filebase=`basename $file`
-    Verbose "Backing up file $filebase"
-    cp $file $BACKUPDUMPDIR
-    startId=$endId
-    file1=`echo $filebase | sed -e 's/\([^0-9]*\)[0-9]*.*/\1/'`
-    file2=`echo $filebase | sed -e 's/[^0-9]*0\?0\?\([0-9]*\).*/\1/'`
-    file3=`echo $filebase | sed -e 's/[^0-9]*[0-9]*\(.*\)/\1/'`
-    #echo $filebase   $file0   $file1   $file2   $file3
-    file2=`echo $((file2+1001)) | sed -e 's/.\(...\)/\1/'`
-    nextfile=$file0/$file1$file2$file3
-    len=`head -c 5 $nextfile 2> /dev/null`
-    if [ $? != 0 ] 
+    endId=000000000
+
+    for file in $DUMPDIR/*.mrc 
+    do
+        file0=`dirname $file`
+        filebase=`basename $file`
+        Verbose "Backing up file $filebase"
+        cp $file $BACKUPDUMPDIR
+        startId=$endId
+        file1=`echo $filebase | sed -e 's/\([^0-9]*\)[0-9]*.*/\1/'`
+        file2=`echo $filebase | sed -e 's/[^0-9]*0\?0\?\([0-9]*\).*/\1/'`
+        file3=`echo $filebase | sed -e 's/[^0-9]*[0-9]*\(.*\)/\1/'`
+        #echo $filebase   $file0   $file1   $file2   $file3
+        file2=`echo $((file2+1001)) | sed -e 's/.\(...\)/\1/'`
+        nextfile=$file0/$file1$file2$file3
+        len=`head -c 5 $nextfile 2> /dev/null`
+        if [ $? != 0 ] 
+            then
+                endId=9999999999
+            else
+                endId=`head -c $len $nextfile | $SCRIPTDIR/getrecord -id`
+        fi
+        #echo $file  $startId  $endId
+        Verbose "Updating file $filebase based on hathi_upd_merged startID=$startId  endID=$endId"
+        #Verbose "marcupdate -min $startId -max $endId -mrc $updatefile -del $updatedelfile $file > $file.updated"
+        $SCRIPTDIR/marcupdate -min $startId -max $endId -mrc $updatefile -del $updatedelfile $file > $file.updated
+        returncode=$?
+        if [ "$returncode" != "0" ] 
         then
-            endId=9999999999
+            Echo "ERROR: Error code $returncode return from marcupdate, exiting before I break things"
+            exit 2 
+        fi
+        if [ -s $file.updated ]
+        then 
+            mv $file.updated $file
         else
-            endId=`head -c $len $nextfile | $SCRIPTDIR/getrecord -id`
-    fi
-    #echo $file  $startId  $endId
-    Verbose "Updating file $filebase based on hathi_upd_merged startID=$startId  endID=$endId"
-    #Verbose "marcupdate -min $startId -max $endId -mrc $updatefile -del $updatedelfile $file > $file.updated"
-    $SCRIPTDIR/marcupdate -min $startId -max $endId -mrc $updatefile -del $updatedelfile $file > $file.updated
-    returncode=$?
-    if [ "$returncode" != "0" ] 
-    then
-        Echo "ERROR: Error code $returncode return from marcupdate, exiting before I break things"
-        exit 2 
-    fi
-    if [ -s $file.updated ]
-    then 
-        mv $file.updated $file
-    else
-        Echo "ERROR: Zero size file produced, exiting before I break things"
-        exit 2
-    fi
-done
+            Echo "ERROR: Zero size file produced, exiting before I break things"
+            exit 2
+        fi
+    done
+fi
 
 for file in `find $INPUTDIR -name 'hathi_upd_*.mrc' -print | sort`
 do 
